server:
  port: 8084
logging:
  level:
    cn.edu.szu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  redisson:
    redis-6379:
      host: 127.0.0.1
      port: 6379
      password:
    redis-6380:
      host: 127.0.0.1
      port: 6380
      password:
    redis-6381:
      host: 127.0.0.1
      port: 6378
      password:
    #超时时间为3s
    timeout: 3000
  main:
    allow-circular-references: false
  datasource:
    url: jdbc:mysql://47.120.13.87:3306/wt_teamwork?useSSL=false
    username: root
    password: 2484101884
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:

    host: 47.120.13.87
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
  application:
    name: teamwork-service
  cloud:
    nacos:
      server-addr: localhost:8848