server:
  port: 8080
spring:
  application:
    name: gateway
  redis:
    host: 47.120.13.87
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: auth-service # 路由标示，必须唯一
          uri: lb://auth-service # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/api/authAndRole/**,/api/auth/**,/api/UserAndRole/**,/api/menu/**,/api/resource/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**,/api/email/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/company_user/**,/api/company/**,/api/group/**
      globalcors: # 跨域设置
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
feign:
  okhttp:
    enabled: true