server:
  port: 8082
logging:
  level:
    cn.edu.szu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  datasource:
    url: jdbc:mysql://47.120.13.87:3306/wt_user?useSSL=false
    username: root
    password: 2484101884
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: localhost:8848
