server:
  port: 8082
logging:
  level:
    cn.edu.szu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 47.120.13.87 # 主机名 http://47.120.13.87:15672/
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: worktogether # 用户名
    password: 123321 # 密码
#  rabbitmq:
#    host: 192.168.150.101 # 主机名
#    port: 15672 # 端口
#    virtual-host: / # 虚拟主机
#    username: itcast # 用户名
#    password: 123321 # 密码
  datasource:
    url: jdbc:mysql://47.120.13.87:3306/wt_user?useSSL=false
    username: root
    password: 2484101884
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.120.13.87
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.qq.com
    port: 587
    username: 2839468956@qq.com
    password: srlcxjtwbbfwddjd
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
    protocol: smtp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
