server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.120.13.87:3306/wt-user?useSSL=false
    username: root
    password: 2484101884
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: auth-service
  cloud:
    nacos:
      server-addr: localhost:8848
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
